### PR TITLE
fix `build_date` issue in `build.rs`

### LINKED ISSUE #1572: `RUBY_COPYRIGHT` is incorrect when `SOURCE_DATE_EPOCH` is set to before year 2019
```console
$ SOURCE_DATE_EPOCH=0 cargo build -q
$ ./target/debug/artichoke --copyright
artichoke - Copyright (c) 2019-1970 Ryan Lopopolo <rjl@hyperbo.la>
```

The copyright year is formatted as **2019-1970**.

I'm not sure what the right behavior is. Maybe if `SOURCE_DATE_EPOCH` is prior to the first commit timestamp of Artichoke, just use 2019? (or maybe if `SOURCE_DATE_EPOCH` points to a date before 2020-01-01T00:00Z?)

Relevant code is here and already has access to the build date and birth date:

https://github.com/artichoke/artichoke/blob/3704e9b6b2b64d731f15d56bf640a17cf043af88/build.rs#L118-L130

Just for fun, here's a more wild one:

```console
$ SOURCE_DATE_EPOCH=-1000000000 cargo build -q
$ ./target/debug/artichoke --copyright
artichoke - Copyright (c) 2019-1938 Ryan Lopopolo <rjl@hyperbo.la>
```

### PR DESCRIPTION
**Pull request by kolharsam**
This PR should help resolve #1572

### CODE REVIEW

**Review by lopopolo — CHANGES_REQUESTED** [review]
Instead of a hard coded `2019` here, can you use `birth_date.year`?

File: build.rs [hunk 1]
```diff
@@ -117,16 +117,21 @@ fn platform(target: &Triple) -> String {
...
     if birth_date.year == build_date.year {
-        format!(
+        return format!(
             "artichoke - Copyright (c) {} Ryan Lopopolo <rjl@hyperbo.la>",
             birth_date.year
-        )
-    } else {
-        format!(
+        );
+    } else if build_date.year >= 2019 {
```
Comment (lopopolo) [inline build.rs]: Sorry for not being specific enough. Do you think this spot needs to be updated to use `birth_date.year` too?

**Review by lopopolo — CHANGES_REQUESTED** [review]

**Review by lopopolo — APPROVED** [review]
I restructured things with a match statement which I think makes this a bit easier to read. In the prior patch, the if and else if branches were overlapping.

**Comment by lopopolo** [comment]
```console
$ SOURCE_DATE_EPOCH=-1000000000 cargo build -q
$ ./target/debug/artichoke --copyright
artichoke - Copyright (c) 2019 Ryan Lopopolo <rjl@hyperbo.la>
$ cargo build -q
$ ./target/debug/artichoke --copyright
artichoke - Copyright (c) 2019-2021 Ryan Lopopolo <rjl@hyperbo.la>
$ SOURCE_DATE_EPOCH=1577106953 cargo build -q
$ ./target/debug/artichoke --copyright
artichoke - Copyright (c) 2019 Ryan Lopopolo <rjl@hyperbo.la>
```
