### PR TITLE
Make artichoke-backend tests pass with `--no-default-features`

### LINKED ISSUE #1008: artichoke-backend tests do not pass with `--no-default-features`
Several tests in `artichoke-backend` fail when building the crate without its default features:

```
failures:
    convert::bytes::tests::bytestring_borrowed
    convert::bytes::tests::bytestring_owned
    convert::string::tests::utf8string_borrowed
    convert::string::tests::utf8string_owned
    extn::core::string::tests::functional
    extn::stdlib::abbrev::tests::functional
    extn::stdlib::json::tests::functional
    extn::stdlib::strscan::tests::functional
    extn::stdlib::uri::tests::functional
    types::tests::parse_array_ruby_type
    types::tests::parse_class_ruby_type
    types::tests::parse_exception_ruby_type
    types::tests::parse_hash_ruby_type
    types::tests::parse_module_ruby_type
    types::tests::parse_object_ruby_type
    value::tests::funcall
```

Fixing this issue will probably involve applying `#[cfg(feature. = "...")]` attributes to tests or modules that are only expected to succeed when certain features are enabled.

See https://github.com/artichoke/artichoke/pull/1007.

## Reproduction

```console
$ cd artichoke-backend
$ cargo test --no-default-features
// snip ...
failures:

---- convert::bytes::tests::bytestring_borrowed stdout ----
thread 'convert::bytes::tests::bytestring_borrowed' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: "NameError", message: "uninitialized constant String::Regexp" })', artichoke-backend/src/convert/bytes.rs:151:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'convert::bytes::tests::bytestring_borrowed' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: "NameError", message: "uninitialized constant String::Regexp" })', artichoke-backend/src/convert/bytes.rs:151:69
thread 'convert::bytes::tests::bytestring_borrowed' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: ([])
Error: "called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: \"NameError\", message: \"uninitialized constant String::Regexp\" })"', /Users/lopopolo/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.9.2/src/tester.rs:178:28

---- convert::bytes::tests::bytestring_owned stdout ----
thread 'convert::bytes::tests::bytestring_owned' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: "NameError", message: "uninitialized constant String::Regexp" })', artichoke-backend/src/convert/bytes.rs:180:69
thread 'convert::bytes::tests::bytestring_owned' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: "NameError", message: "uninitialized constant String::Regexp" })', artichoke-backend/src/convert/bytes.rs:180:69
thread 'convert::bytes::tests::bytestring_owned' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: ([])
Error: "called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: \"NameError\", message: \"uninitialized constant String::Regexp\" })"', /Users/lopopolo/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.9.2/src/tester.rs:178:28

---- convert::string::tests::utf8string_borrowed stdout ----
thread 'convert::string::tests::utf8string_borrowed' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: "NameError", message: "uninitialized constant String::Regexp" })', artichoke-backend/src/convert/string.rs:118:14
thread 'convert::string::tests::utf8string_borrowed' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: "NameError", message: "uninitialized constant String::Regexp" })', artichoke-backend/src/convert/string.rs:118:14
thread 'convert::string::tests::utf8string_borrowed' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: ("")
Error: "called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: \"NameError\", message: \"uninitialized constant String::Regexp\" })"', /Users/lopopolo/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.9.2/src/tester.rs:178:28

---- convert::string::tests::utf8string_owned stdout ----
thread 'convert::string::tests::utf8string_owned' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: "NameError", message: "uninitialized constant String::Regexp" })', artichoke-backend/src/convert/string.rs:151:14
thread 'convert::string::tests::utf8string_owned' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: "NameError", message: "uninitialized constant String::Regexp" })', artichoke-backend/src/convert/string.rs:151:14
thread 'convert::string::tests::utf8string_owned' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: ("")
Error: "called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: \"NameError\", message: \"uninitialized constant String::Regexp\" })"', /Users/lopopolo/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.9.2/src/tester.rs:178:28

---- extn::core::string::tests::functional stdout ----
thread 'extn::core::string::tests::functional' panicked at 'String tests failed with message: "uninitialized constant Regexp" and backtrace:
"(eval):16:in string_match_operator\n(eval):6:in spec\n(eval):1"', artichoke-backend/src/extn/core/string/mod.rs:23:13

---- extn::stdlib::abbrev::tests::functional stdout ----
thread 'extn::stdlib::abbrev::tests::functional' panicked at 'Abbrev tests failed with message: "uninitialized constant String::Regexp" and backtrace:
"(eval):127:in []\n/src/lib/abbrev.rb:85:in abbrev\n(eval):27:in downto\n/src/lib/abbrev.rb:84:in abbrev\n(eval):653:in each\n/src/lib/abbrev.rb:81:in abbrev\n(eval):24:in abbrev\n(eval):8:in spec\n(eval):1"', artichoke-backend/src/extn/stdlib/abbrev/mod.rs:29:13

---- extn::stdlib::json::tests::functional stdout ----
thread 'extn::stdlib::json::tests::functional' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: "NameError", message: "uninitialized constant Regexp" })', artichoke-backend/src/extn/stdlib/json/mod.rs:39:46

---- extn::stdlib::uri::tests::functional stdout ----
thread 'extn::stdlib::uri::tests::functional' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: "NameError", message: "uninitialized constant Regexp" })', artichoke-backend/src/extn/stdlib/uri/mod.rs:55:46

---- extn::stdlib::strscan::tests::functional stdout ----
thread 'extn::stdlib::strscan::tests::functional' panicked at 'StringScanner tests failed with message: "uninitialized constant Regexp" and backtrace:
"(eval):44:in test_strscan\n(eval):6:in spec\n(eval):1"', artichoke-backend/src/extn/stdlib/strscan/mod.rs:29:13

---- types::tests::parse_class_ruby_type stdout ----
thread 'types::tests::parse_class_ruby_type' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: "NameError", message: "uninitialized constant Math" })', artichoke-backend/src/types.rs:200:56

---- types::tests::parse_exception_ruby_type stdout ----
thread 'types::tests::parse_exception_ruby_type' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: "NameError", message: "uninitialized constant Math" })', artichoke-backend/src/types.rs:283:60

---- types::tests::parse_array_ruby_type stdout ----
thread 'types::tests::parse_array_ruby_type' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: "NameError", message: "uninitialized constant Regexp" })', artichoke-backend/src/types.rs:244:58

---- types::tests::parse_hash_ruby_type stdout ----
thread 'types::tests::parse_hash_ruby_type' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: "NameError", message: "uninitialized constant Regexp" })', artichoke-backend/src/types.rs:256:53

---- types::tests::parse_module_ruby_type stdout ----
thread 'types::tests::parse_module_ruby_type' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: "NameError", message: "uninitialized constant Math" })', artichoke-backend/src/types.rs:209:41

---- types::tests::parse_object_ruby_type stdout ----
thread 'types::tests::parse_object_ruby_type' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: "NameError", message: "uninitialized constant ENV" })', artichoke-backend/src/types.rs:189:39

---- value::tests::funcall stdout ----
thread 'value::tests::funcall' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CaughtException { value: Value(<Ruby Exception>), name: "NameError", message: "uninitialized constant String::Regexp" })', artichoke-backend/src/value.rs:642:69


failures:
    convert::bytes::tests::bytestring_borrowed
    convert::bytes::tests::bytestring_owned
    convert::string::tests::utf8string_borrowed
    convert::string::tests::utf8string_owned
    extn::core::string::tests::functional
    extn::stdlib::abbrev::tests::functional
    extn::stdlib::json::tests::functional
    extn::stdlib::strscan::tests::functional
    extn::stdlib::uri::tests::functional
    types::tests::parse_array_ruby_type
    types::tests::parse_class_ruby_type
    types::tests::parse_exception_ruby_type
    types::tests::parse_hash_ruby_type
    types::tests::parse_module_ruby_type
    types::tests::parse_object_ruby_type
    value::tests::funcall

test result: FAILED. 175 passed; 16 failed; 0 ignored; 0 measured; 0 filtered out
```

### PR DESCRIPTION
**Pull request by silathdiir**
Closes #1008

### CODE REVIEW

File: artichoke-backend/src/types.rs [hunk 1]
```diff
@@ -197,17 +200,23 @@ mod tests {
         assert_eq!(Ruby::Class, types::ruby_from_mrb_value(builtin.inner()));
         let data = interp.eval(b"Array").unwrap();
         assert_eq!(Ruby::Class, types::ruby_from_mrb_value(data.inner()));
-        let source = interp.eval(b"Math::DomainError").unwrap();
-        assert_eq!(Ruby::Class, types::ruby_from_mrb_value(source.inner()));
+        #[cfg(feature = "stlib-cmath")]
```
Comment (lopopolo) [inline artichoke-backend/src/types.rs]: I think this should be the `Math` core module:

```suggestion
        #[cfg(feature = "core-math")]
```

File: artichoke-backend/src/types.rs [hunk 2]
```diff
@@ -197,17 +200,23 @@ mod tests {
...
     }
 
     #[test]
     fn parse_module_ruby_type() {
         let mut interp = interpreter().unwrap();
         let builtin = interp.eval(b"Comparable").unwrap();
         assert_eq!(Ruby::Module, types::ruby_from_mrb_value(builtin.inner()));
-        let data = interp.eval(b"Math").unwrap();
-        assert_eq!(Ruby::Module, types::ruby_from_mrb_value(data.inner()));
+        #[cfg(feature = "stlib-cmath")]
```
Comment (lopopolo) [inline artichoke-backend/src/types.rs]: I think this should be the `Math` core module:

```suggestion
        #[cfg(feature = "core-math")]
```

File: artichoke-backend/src/types.rs [hunk 3]
```diff
@@ -278,9 +293,12 @@ mod tests {
         assert_eq!(Ruby::Exception, types::ruby_from_mrb_value(root.inner()));
         let stderror = interp.eval(b"StandardError.new").unwrap();
         assert_eq!(Ruby::Exception, types::ruby_from_mrb_value(stderror.inner()));
-        let index = interp.eval(b"IndexError.new").unwrap();
-        assert_eq!(Ruby::Exception, types::ruby_from_mrb_value(index.inner()));
-        let domain = interp.eval(b"Math::DomainError.new").unwrap();
-        assert_eq!(Ruby::Exception, types::ruby_from_mrb_value(domain.inner()));
+        #[cfg(feature = "stlib-cmath")]
```
Comment (lopopolo) [inline artichoke-backend/src/types.rs]: I think this should be the `Math` core module:

```suggestion
        #[cfg(feature = "core-math")]
```

File: artichoke-backend/src/convert/string.rs [hunk 4]
```diff
@@ -96,6 +96,7 @@ mod tests {
         }
 
         #[allow(clippy::needless_pass_by_value)]
+        #[cfg(feature = "core-regexp")]
```
Comment (lopopolo) [inline artichoke-backend/src/convert/string.rs:99]: Note to self: This feature dependency is because `String#[]` is implemented in pure Ruby and depends on `Regexp`.

https://github.com/artichoke/artichoke/blob/44b60ed9a8f3922cfac6c8e07ecc343e3091bc3e/artichoke-backend/src/extn/core/string/string.rb#L184-L197

File: artichoke-backend/src/convert/string.rs [hunk 5]
```diff
@@ -128,6 +129,7 @@ mod tests {
...
```
Comment (lopopolo) [inline artichoke-backend/src/convert/string.rs:132]: Note to self: This feature dependency is because `String#[]` is implemented in pure Ruby and depends on `Regexp`.

https://github.com/artichoke/artichoke/blob/44b60ed9a8f3922cfac6c8e07ecc343e3091bc3e/artichoke-backend/src/extn/core/string/string.rb#L184-L197

File: artichoke-backend/src/extn/core/string/mod.rs [hunk 6]
```diff
@@ -5,6 +5,7 @@ pub mod trampoline;
 pub struct String;
 
 #[cfg(test)]
+#[cfg(feature = "core-regexp")]
```
Comment (lopopolo) [inline artichoke-backend/src/extn/core/string/mod.rs:8]: Note to self: This feature dependency is because `String#[]` is implemented in pure Ruby and depends on `Regexp`.

https://github.com/artichoke/artichoke/blob/44b60ed9a8f3922cfac6c8e07ecc343e3091bc3e/artichoke-backend/src/extn/core/string/string.rb#L184-L197

File: artichoke-backend/src/types.rs [hunk 7]
```diff
@@ -278,9 +293,12 @@ mod tests {
...
+        {
+            let index = interp.eval(b"IndexError.new").unwrap();
+            assert_eq!(Ruby::Exception, types::ruby_from_mrb_value(index.inner()));
+            let domain = interp.eval(b"Math::DomainError.new").unwrap();
+            assert_eq!(Ruby::Exception, types::ruby_from_mrb_value(domain.inner()));
+        }
```
Comment (lopopolo) [inline artichoke-backend/src/types.rs]: This index error doesn't need to be wrapped in the `cfg`. `IndexError` is a core `Exception` type.
```suggestion
        let index = interp.eval(b"IndexError.new").unwrap();
        assert_eq!(Ruby::Exception, types::ruby_from_mrb_value(index.inner()));
        #[cfg(feature = "stlib-cmath")]
        {
            let domain = interp.eval(b"Math::DomainError.new").unwrap();
            assert_eq!(Ruby::Exception, types::ruby_from_mrb_value(domain.inner()));
        }
```

**Review by lopopolo — CHANGES_REQUESTED** [review]
Thanks for the PR @silathdiir. This looks like a good approach.

There are a couple of feature flags that I think we can fix up. Let me know what you think.

**Comment by lopopolo** [comment]
@silathdiir for the `core-math` changes, I think we should be able to see the current change set fail by running:

```bash
cd artichoke-backend
cargo test --no-default-features --features stdlib-cmath
```

Flipping the `cfg`s to `core-math` and retesting with the below should see the build pass:

```bash
cd artichoke-backend
cargo test --no-default-features --features core-math
```

**Review by lopopolo — APPROVED** [review]
Looks good. Thanks for making these changes.
