### PR TITLE
Change PartialEq for EncodedString

### LINKED ISSUE #2193: `String#==` does not work the same way as MRI expects
Generated from https://github.com/artichoke/artichoke/pull/2182#issuecomment-1257154057

Ruby docs ref: https://ruby-doc.org/core-3.1.2/String.html#method-i-3D-3D. Relevant part:

> Returns true if object has the **same length** and content; as self; false otherwise.

And it looks like we're currently just comparing the internal `bytes` at present:
- [spinoso-string](https://github.com/artichoke/artichoke/blob/2db53033309c3e4f923fdea960d0884c4b47d1c8/spinoso-string/src/eq.rs)
- [artichoke-backend](https://github.com/artichoke/artichoke/blob/trunk/artichoke-backend/src/extn/core/string/trampoline.rs#L315-L333)

From MRI:

```console
[3.1.2]> "A" == "A"
=> true
[3.1.2]> "A".b == "A"
=> true
[3.1.2]> "\u{1F600}" == "\u{1F600}"
=> true
[3.1.2]> "\u{1F600}".b == "\u{1F600}"
=> false
```

Artichoke:
```console
=> true
>>> "A" == "A"
=> true
>>> "A".b == "A"
=> true
>>> "\u{1F600}" == "\u{1F600}"
=> true
>>> "\u{1F600}".b == "\u{1F600}"
=> true
```

## Solutions ideas

Rust psuedo-ish code change:

```rust
self.as_bytes() == other.as_bytes() && self.len() == other.len()
```

:point_up: I imagine `len()` would be fine since it is encoding aware, and should return the number of codepoints vs. bytes in the above.

The question I have is, should it be in `spinoso-string`, or in `string/trampoline.rs`. `spinoso-string` does mention `The Ruby String class`, which means we could assume that RStrings should do equality in this way - however it feels a little bit unexpected/hidden.

### PR DESCRIPTION
**Pull request by moozzi**
Fixes #2193

### CODE REVIEW

File: spinoso-string/src/enc/mod.rs [hunk 1]
```diff
@@ -69,7 +69,7 @@ impl PartialEq for EncodedString {
         // [3.0.2] > s == t
         // => true
         // ```
-        *self.as_slice() == *other.as_slice()
+        *self.as_slice() == *other.as_slice() && self.char_len() == other.char_len()
```
Comment (lopopolo) [inline spinoso-string/src/enc/mod.rs]: this test can be made cheaper by comparing the encodings I think, but this works for now.

**Review by lopopolo — CHANGES_REQUESTED** [review]
Can you add an integration test for this here:

https://github.com/artichoke/artichoke/blob/84ac85cc0750ea066f7155574b4f7a136b623041/artichoke-backend/src/extn/core/string/string_test.rb#L5-L17

I think asserting that `"太贵了!!" != "太贵了!!".b` should do the trick:

```
[3.1.2] > "太贵了!!" == "太贵了!!".b
=> false
```

once the test is in that file, you `cargo test` will run it under artichoke and `ruby artichoke-backend/src/extn/core/string/string_test.rb` can be used to test it under MRI.

File: spinoso-string/src/enc/mod.rs (hunk 1 above)
Comment (b-n) [reply spinoso-string/src/enc/mod.rs]:
```suggestion
        (*self.as_slice() == *other.as_slice() && self.encoding() == other.encoding()) ||
            (*self.as_slice() == * other.as_slice() && self.encoding() != self.encoding && self.is_ascii_only() && other.is_ascii_only())
```

:point_up: I didn't test this, so it's likely invalid syntax, however I think this is valid for at least the 3 encodings supported by `spinoso-string`

```console
irb(main):001:0> a = "\x7f"
=> "\u007F"
irb(main):002:0> b = a.b
=> "\x7F"
irb(main):003:0> a.encoding
=> #<Encoding:UTF-8>
irb(main):004:0> b.encoding
=> #<Encoding:ASCII-8BIT>
irb(main):005:0> a == b
=> true
irb(main):006:0> c = "\x80"
=> "\x80"
irb(main):007:0> d = c.b
=> "\x80"
irb(main):008:0> c == d
=> false
```

Comment (moozzi) [reply spinoso-string/src/enc/mod.rs]: @b-n You meant `self.encoding() != other.encoding()` not `self.encoding() != self.encoding` right?

Comment (b-n) [reply spinoso-string/src/enc/mod.rs]: Ah sorry, missed this question. I will reformat my suggestion since it's hard to see what it was trying to do :grimacing: 

```suggestion
        if self.encoding() == other.encoding() {
            *self.as_slice() == *other.as_slice()
        } else {
            *self_as_slice() == *other.as_slice() && self.is_ascii_only() && other.is_ascii_only()
        }
```

I noticed that if two ruby strings contain exactly the same characters, and so long as they are only ascii characters (0..=127) then it says it's the "same", even if the encoding doesn't match.

**Comment by lopopolo** [comment]
sorry to let this PR languish @AI-Mozi. I hope you don't mind that I've fixed the RuboCop lint errors on your branch a rebased to latest trunk to get the build passing.

File: spinoso-string/src/enc/mod.rs (hunk 1 above)
Comment (lopopolo) [reply spinoso-string/src/enc/mod.rs]: @b-n I've made this change. let me know what you think

**Review by lopopolo — APPROVED** [review]

File: spinoso-string/src/enc/mod.rs (hunk 1 above)
Comment (b-n) [reply spinoso-string/src/enc/mod.rs]: Rust match block++, very very very nice.

**Review by b-n — APPROVED** [review]

**Comment by lopopolo** [comment]
thanks for the teamwork on this one folks!
