### PR TITLE
Fix Regexp#initialize to raise FrozenError instead of FrozenError on reinitializing literal Regexp in Ruby 3

### LINKED ISSUE #1985: Calling `Regexp#initialize` on an initialized `Regexp` should raise `FrozenError`
```
[3.1.2] > r = /abc/
=> /abc/
[3.1.2] > r.send(:initialize, /xyz/)
(irb):2:in `initialize': can't modify frozen Regexp: /abc/ (FrozenError)
        from (irb):2:in `<main>'
        from /usr/local/var/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
        from /usr/local/var/rbenv/versions/3.1.2/bin/irb:25:in `load'
        from /usr/local/var/rbenv/versions/3.1.2/bin/irb:25:in `<main>'
[3.1.2] > r.send(:initialize, Regexp.compile('abc'))
(irb):3:in `initialize': can't modify frozen Regexp: /abc/ (FrozenError)
        from (irb):3:in `<main>'
        from /usr/local/var/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
        from /usr/local/var/rbenv/versions/3.1.2/bin/irb:25:in `load'
        from /usr/local/var/rbenv/versions/3.1.2/bin/irb:25:in `<main>'
```

With the change in Ruby version in #1978, update this code and fix the TODO:

https://github.com/artichoke/artichoke/blob/14533f348eee00ba62e8ee2c4e57ac8b0b735bdd/artichoke-backend/src/extn/core/regexp/trampoline.rs#L13-L20

### PR DESCRIPTION
**Pull request by mmizutani**
Since Ruby 3.0, Regexp literals are frozen by default, this PR changes the type of the error returned when one tries to re-initialize Regexp literals from `SecurityError` to `FrozenError`. 

```bash
$ RBENV_VERSION=2.7.6 ruby -ve 'p(/abc/.frozen?)'
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin21]
false

$ RBENV_VERSION=3.1.2 ruby -ve 'p(/abc/.frozen?)'
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
true

$ RBENV_VERSION=2.7.6 ruby -ve '/abc/.send(:initialize, /xyz/)'
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin21]
Traceback (most recent call last):
	1: from -e:1:in `<main>'
-e:1:in `initialize': can't modify literal regexp (SecurityError)

$ RBENV_VERSION=3.1.2 ruby -ve '/abc/.send(:initialize, /xyz/)'
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
-e:1:in `initialize': can't modify frozen Regexp: /abc/ (FrozenError)
	from -e:1:in `<main>'
```

This PR updates the following tests and implementations of `Regexp`:

1. Add a test to ensure that Regexp literals are frozen by default.
1. Add a test to ensure that re-initializing Regexp literals raises `FrozenError`.
1. Update the initializer of the `Regexp` backend so that 
    - `Regexp` literals are frozen upon creation.
    - `FrozenError` is raised when one tries to re-initialize `Regexp` literals.

With these modifications, the following behaviors are changed:

```diff
$ cargo run --bin artichoke -q -- -e 'p(/abc/.frozen?)' 
- false
+ true
```

```diff
$ cargo run --bin artichoke -q -- -e 'p(/abc/.send(:initialize, "xyz"))'
Traceback (most recent call last):
        2: from -e:1
- -e:1:in initialize: can't modify literal regexp (SecurityError)
+ -e:1:in initialize: can't modify literal regexp (FrozenError)
```

Fixes #1985.

### CODE REVIEW

**Comment by lopopolo** [comment]
Thanks for the PR @mmizutani. It'd be great to add a test for these cases too:

```
$ ruby -ve 'p(Regexp.compile("abc").frozen?)'
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
false
$ ruby -ve 'p(Regexp.compile("abc").send(:initialize, "xyz"))'
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
-e:1:in `initialize': already initialized regexp (TypeError)
        from -e:1:in `<main>'
```

**Comment by mmizutani** [comment]
@lopopolo 
I am wondering in which directory I should place such a custom Ruby conformance test. 
It seems that the Ruby spec tests in `spec-runner/vendor/spec/core/regexp/` should be kept as the original.

**Comment by lopopolo** [comment]
> It seems that the Ruby spec tests in `spec-runner/vendor/spec/core/regexp/` should be kept as the original.

yup that's right, these are vendored from upstream ruby/spec.

> @lopopolo I am wondering in which directory I should place such a custom Ruby conformance test.

You can create a Ruby conformance test for `Regexp` in a new Ruby file here: `artichoke-backend/src/extn/core/regexp/regexp_test.rb`.

For an example of how this looks, take a look at `Kernel`:

https://github.com/artichoke/artichoke/blob/995b8caf09dfbfba84b1ad001e024fe427d432a6/artichoke-backend/src/extn/core/kernel/kernel_test.rb#L5-L20

and the harness in `extn/core/kernel/mod.rs`:

https://github.com/artichoke/artichoke/blob/995b8caf09dfbfba84b1ad001e024fe427d432a6/artichoke-backend/src/extn/core/kernel/mod.rs#L9-L24

**Comment by lopopolo** [comment]
@mmizutani it looks like by adding these tests you've found a bug!

It looks like the regexp options that indicate the regexp is a literal are not making it through somehow.

I added this diff:

```diff
diff --git i/artichoke-backend/src/extn/core/regexp/trampoline.rs w/artichoke-backend/src/extn/core/regexp/trampoline.rs
index 2addeaa0ce..ef2f04135e 100644
--- i/artichoke-backend/src/extn/core/regexp/trampoline.rs
+++ w/artichoke-backend/src/extn/core/regexp/trampoline.rs
@@ -11,15 +11,15 @@ pub fn initialize(
     mut into: Value,
 ) -> Result<Value, Error> {
     if let Ok(existing) = unsafe { Regexp::unbox_from_value(&mut into, interp) } {
-        let options = Options::from(existing.options());
-        if options.is_literal() {
+        let options = dbg!(Options::from(existing.options()));
+        if dbg!(options.is_literal()) {
             // NOTE: In Ruby 3.0.0+, this branch should return a `FrozenError`.
             return Err(SecurityError::with_message("can't modify literal regexp").into());
         }
         return Err(TypeError::with_message("already initialized regexp").into());
     }
     let (options, encoding) = interp.try_convert_mut((options, encoding))?;
-    let regexp = Regexp::initialize(interp, pattern, options, encoding)?;
+    let regexp = Regexp::initialize(interp, pattern, dbg!(options), encoding)?;
     Regexp::box_into_value(regexp, into, interp)
 }

```

and ran this in `airb`:

```console
$ cargo run --bin airb -q
artichoke 0.1.0-pre.0 (2022-08-11 revision 6046) [x86_64-apple-darwin]
[rustc 1.63.0 (4b91a6ea7 2022-08-08) on x86_64-apple-darwin]
>>> /abc/
[artichoke-backend/src/extn/core/regexp/trampoline.rs:22] options = None
=> /abc/
>>> /abc/.send(:initialize, 'abc')
[artichoke-backend/src/extn/core/regexp/trampoline.rs:22] options = None
[artichoke-backend/src/extn/core/regexp/trampoline.rs:14] Options::from(existing.options()) = Options {
    flags: (empty),
}
[artichoke-backend/src/extn/core/regexp/trampoline.rs:15] options.is_literal() = false
Traceback (most recent call last):
        2: from (airb):2
        1: from (airb):2:in initialize
TypeError (already initialized regexp)
```

**Comment by lopopolo** [comment]
So sorry for making this PR much more difficult with the breakage in the parser 😅 Thank you for writing the test that found this bug!

The fix to the parser so `options.is_literal()` behaves as expected is merged:

- https://github.com/artichoke/artichoke/pull/2084

If you rebase this PR to include it, I think your tests will pass. #2084 includes a minimal `Regexp` conformance test harness, so you might have some rebase conflicts. Please rebase instead of merging with `trunk`.

One other thing, I noticed the `rustfmt` check is failing in CI around import ordering. Artichoke uses nightly `rustfmt` with an experimental option to reorder imports. If you'd like to fix this up locally, you can run `bundle exec rake fmt:rust`. This rake task will handle installing the nightly toolchain and using nightly `rustfmt`.

Thanks @mmizutani for the PR and sorry for the difficulty here 🙇 Hopefully we can get this merged soon.

File: artichoke-backend/src/extn/core/regexp/regexp_test.rb [hunk 1]
```diff
@@ -13,8 +14,24 @@ def regexp_initialize_already_init_literal
...
+
+  r = /abc/in
+  begin
+    r.send(:initialize, '/xyz/')
+    raise 'expected FrozenError'
+  rescue FrozenError => e
+    raise "got message: #{e.message}" unless e.message == "can't modify literal regexp"
+  end
+
+  r = /abc/in
```
Comment (lopopolo) [inline artichoke-backend/src/extn/core/regexp/regexp_test.rb:30]: I think for this test, it's the receiver that needs to not be a literal.

```suggestion
  r = Regexp.compile('abc')
```

File: artichoke-backend/src/extn/core/regexp/regexp_test.rb [hunk 2]
```diff
@@ -29,4 +46,17 @@ def regexp_initialize_already_init_compiled
...
 
+# Since Ruby 3.0, Regexp literals are frozen by default.
+# https://github.com/ruby/ruby/pull/2705
+# https://github.com/ruby/ruby/pull/3676
+# Non-literal Regexp objects are still unfrozen by default.
+def regexp_initialize_only_literals_frozen_by_default
+  raise unless /abc/.frozen?
+
+  s = 'abc'
+  raise unless /#{s}/.frozen?
```
Comment (lopopolo) [inline artichoke-backend/src/extn/core/regexp/regexp_test.rb:73]: I'm not sure this will pass due to some limitations of the mruby parser. If it fails, please comment this out and add a FIXME comment.

File: artichoke-backend/src/extn/core/regexp/trampoline.rs [hunk 3]
```diff
@@ -12,14 +12,21 @@ pub fn initialize(
...
-    Regexp::box_into_value(regexp, into, interp)
+    let result = Regexp::box_into_value(regexp, into, interp);
+    if let Some(options) = options {
+        if options.is_literal() {
+            let mut value = result?;
+            value.freeze(interp)?;
+            return Ok(value);
+        }
+    }
+    result
```
Comment (lopopolo) [inline artichoke-backend/src/extn/core/regexp/trampoline.rs]: can we short circuit return with `?` and use `matches!` here? It will remove a level of nesting with the `if`s.

```suggestion
    let mut value = Regexp::box_into_value(regexp, into, interp)?;
    if matches!(options, Some(options) if options.is_literal()) {
        value.freeze(interp)?;
    }
    Ok(value)
```

**Review by lopopolo — CHANGES_REQUESTED** [review]

File: artichoke-backend/src/extn/core/regexp/trampoline.rs (hunk 3 above)
Comment (mmizutani) [reply artichoke-backend/src/extn/core/regexp/trampoline.rs]: Thank you for the advice. The suggested syntax is much more succinct.

File: artichoke-backend/src/extn/core/regexp/regexp_test.rb (hunk 1 above)
Comment (mmizutani) [reply artichoke-backend/src/extn/core/regexp/regexp_test.rb:30]: This test corresponds to the second case mentioned in #1985.

```bash
[3.1.2] > r = /abc/
=> /abc/
...
[3.1.2] > r.send(:initialize, Regexp.compile('abc'))
(irb):3:in `initialize': can't modify frozen Regexp: /abc/ (FrozenError)
        from (irb):3:in `<main>'
        from /usr/local/var/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
        from /usr/local/var/rbenv/versions/3.1.2/bin/irb:25:in `load'
        from /usr/local/var/rbenv/versions/3.1.2/bin/irb:25:in `<main>'
```

File: artichoke-backend/src/extn/core/regexp/trampoline.rs [hunk 4]
```diff
@@ -169,3 +172,23 @@ pub fn to_s(interp: &mut Artichoke, mut regexp: Value) -> Result<Value, Error> {
...
     interp.try_convert_mut(s)
 }
+
+#[cfg(test)]
+mod tests {
+    use super::*;
+    use crate::test::prelude::*;
+
+    #[test]
+    fn should_raise_frozen_error() {
```
Comment (lopopolo) [inline artichoke-backend/src/extn/core/regexp/trampoline.rs:182]: I think this is the first test that has ever been added to a `trampoline` module. Thanks for blazing the trail!

We should add tests like these to the trampolines for `Array` and `String` too.

**Review by lopopolo — APPROVED** [review]

File: artichoke-backend/src/extn/core/regexp/trampoline.rs (hunk 4 above)
Comment (lopopolo) [reply artichoke-backend/src/extn/core/regexp/trampoline.rs:182]: Filed a ticket here:

- https://github.com/artichoke/artichoke/issues/2086

**Comment by lopopolo** [comment]
Thanks for the PR @mmizutani! merging.

File: artichoke-backend/src/extn/core/regexp/trampoline.rs (hunk 4 above)
Comment (mmizutani) [reply artichoke-backend/src/extn/core/regexp/trampoline.rs:182]: Thank you for setting up pre-conditions for this PR as well as guiding me in the right direction.
It was a good opportunity to get a bit familiar with the internals of Artichoke.
